# Generated by Django 4.2.8 on 2024-05-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyresponse',
            name='question_2',
            field=models.CharField(choices=[('a', '재난'), ('b', '외계인'), ('c', '중세 권력 싸움'), ('d', '탐정'), ('e', '가족 드라마'), ('f', '권력싸움'), ('g', '귀여움'), ('h', '즐거움'), ('i', '상상력'), ('j', '스릴')], max_length=1),
        ),
    ]
