# Generated by Django 4.2.8 on 2024-05-18 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_movie_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='total_audience_count',
            field=models.IntegerField(null=True),
        ),
    ]
